#!/bin/bash

dir=./nejni-bot-venv
if ! [[ -d $dir ]] ; then
	echo "error: venv dir not found: creating and installing dependencies"
	python3 -m venv $dir
	./pip install discord.py
fi

# sleep for a little bit to fix the systemd init script
sleep 5
./python3 ./main.py
